### ISSUE TITLE
picking random voice example

### ISSUE THREAD

**Issue by shiffman** [IDMNYU/p5.js-speech#13]
Hi @rev3rend, thanks again for helping me understand the library this morning. I have one example where I want to pick a random new voice, so I am not setting a voice initially but I do want a callback for when the voices are available, i.e.:

```javascript
speech = new p5.Speech(voiceReady);
function voiceReady() {
  let voice = random(speech.voices);
  speech.setVoice(voice.name);
  speech.speak('Hello');
}
```
How do you feel about adding this extra one line check for the `p5.Speech` constructor?

```javascript
if (_dv !== undefined && typeof _dv == 'function') this.onLoad = _callback; // NEW!
else if (_dv !== undefined) this.initvoice = _dv;
if (_callback !== undefined) this.onLoad = _callback;
```

Alternatively I can just write my code like so which is ok too:

```javascript
  speech = new p5.Speech();
  speech.onLoad = voiceReady;
```

Let me know which you prefer and I can adjust my example or submit a pull request with just the one line.

**Comment by simon-tiger** [comment]
It actually was `_dv instanceof Function` before, but I sead it's actually `typeof`.

**Comment by simon-tiger** [comment]
Dan has got another example using `p5.SpeechRec`:
```javascript
speechRec = new p5.SpeechRec(gotSpeech);
let continuous = true;
let interimResults = false;
speechRec.start(continuous, interimResults);
function gotSpeech(speech) {
  console.log(speech);
  if (speech.success) {
    createP(speech.text);
  }
```
, And it's got the same problem.

**Comment by shiffman** [comment]
I sorted this out and will just use the API as is, thanks for your patience!
