### ISSUE TITLE
I  have a issue about the language

### ISSUE THREAD

**Issue by lucaspdroz** [IDMNYU/p5.js-speech#5]
Well I  have a issue about the language, it's no a great issue, but it's about the `setLang(" ");` 

I don't understant if you put the `setLang()` when you declares the variable like:
`var myVoice = new p5.Speech().setLang("Google UK English Male");` or
`var myVoice = new p5.Speech().setLang("en-UK");`

or in the output of the variable:
`myVoice.setLang("en-UK").myVoice.speak('Hello!!!');`

I'm a beginner  with p5.js and i'm using to a personal project

I Really thank you  to make this speech recognition library

**Comment by AlcaDesign** [comment]
`.setLang()` is for BCP 47 language tags like `'en-UK'` for instance. ([RFC](https://tools.ietf.org/html/bcp47)) ([MDN](https://developer.mozilla.org/en-US/docs/Web/API/SpeechSynthesisUtterance/lang))

For voices you want `.setVoice()` with one of the voices from the array at `.voices`.

```javascript
let myVoice = new p5.Speech();

myVoice.setLang('en-UK');
myVoice.setVoice('Google UK English Male');

myVoice.speak('Hello!');
```
